name: ${project.artifactId}
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
main: net.mattlabs.crewcore.CrewCore
softdepend:
  - DiscordSRV
  - Vault
loadbefore:
  - DiscordSRV

permissions:
  crewcore.nonmember:
    description: Given to nonmembers.
  crewcore.member:
    description: Given to members.
  crewcore.moderator:
    description: Given to moderators.
  crewcore.admin:
    description: Given to admins.