name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
main: net.mattlabs.crewcore.CrewCore
commands:
  ender:
    description: Info on Ender Dragon fight.
    usage: '/ender'